name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@v1.1.1
        with:
          packages: texlive-latex-base
          version: 1.07

      - run: ls -l /var/cache/apt/archives

      - run: dpkg -c /var/cache/apt/archives/texlive-base_2019.20200218-1_all.deb

      - run: dpkg -e /var/cache/apt/archives/texlive-base_2019.20200218-1_all.deb

      - run: head -n 100000 DEBIAN/*

      - run: kpsewhich fmtutil.cnf || true

      - run: kpsewhich -engine=pdftex pdflatex.fmt || true

      - run: ls -l /usr/share/texmf/web2c/fmtutil.cnf || true

      - run: ls -l /var/lib/texmf/fmtutil.cnf-DEBIAN || true

      - run: cat /var/lib/texmf/fmtutil.cnf-DEBIAN || true

      - run: pdflatex test.tex

      - uses: actions/upload-artifact@v3
        with:
          name: doc
          path: test.pdf
          if-no-files-found: error
